# DISCLAIMER: 
# This code was previously part of Joris Heemskerks Bachelors thesis, 
# and is being re-used here. All rights are reserved to Joris Heemskerk, 
# and Technolution BV, Gouda NL. Joris was granted the rights to use and 
# modify this code, at the express notion that a disclaimer was put in.

# Default environment yaml file
# NOTE: See assignment_1/config/config_validation_template.py for the 
# parameter restrictions.

general:
    num_data_workers: 0 # Number of workers preparing batches.
    ommited_sensors: [3, 57, 61, 73, 105, 144, 188, 193, 224, 236] # The sensors excluded from training and testing.
jobs:
    job0:
        ### Data ###
        dataset: cross # Can be from [intra, cross]
        window_size: [32, 1024]
        stride: 1024 # Replaced by window_size when tune == true
        downsample_factor: [1, 6]
        lazy: true
        train_val_split: [.8, .2] # Only used if k_folds > 1
        batch_size: [8, 128]
        ### Model ###
        model: "baseline" # Can be from: [baseline, eegnet, eegnettransformer, meggpt, meggcnet, all]
        model_params: # Contents depend on the model used
            dropout: [0.0, 0.75]
        optimiser: "adam"
        learning_rate: [0.000001, 0.001]
        weight_decay: [0.000001, 0.001]
        n_epochs: 30
        k_folds: 3  # use 1 to ignore, 3 to fold over people in the cross dataset, and 8 to use 1 file per task for val
        ## Tune ###
        tune: true
        n_trials: 40
        n_startup_trials: 7
        min_epochs: 10
        reduction_factor: 3
