# DISCLAIMER: 
# This code was previously part of Joris Heemskerks Bachelors thesis, 
# and is being re-used here. All rights are reserved to Joris Heemskerk, 
# and Technolution BV, Gouda NL. Joris was granted the rights to use and 
# modify this code, at the express notion that a disclaimer was put in.

# Default environment yaml file
# NOTE: See assignment_1/config/config_validation_template.py for the 
# parameter restrictions.

general:
    num_data_workers: 4 # Number of workers preparing batches.
jobs:
    job0:
        ### Data ###
        dataset: cross # Can be from [intra, cross]
        window_size: [32]
        stride: [32]
        downsample_factor: 4
        lazy: true
        train_val_split: [.8, .2] # Only used if k_folds > 1
        batch_size: [128]
        ### Model ###
        model: "baseline" # Can be from: [baseline, eegnet, eegnettransformer, all]
        model_params: # Contents depend on the model used
            hidden_size: 64
            num_layers: 1
        optimiser: "adam"
        learning_rate: [0.0001]
        weight_decay: [0.0001]
        n_epochs: 10
        k_folds: 3  # use 1 to ignore, 3 to fold over people in the cross dataset, and 8 to use 1 file per task for val
        ### Tune ###
        # tune: true
        # n_trials: 3
        # n_startup_trials: 0
