# DISCLAIMER: 
# This code was previously part of Joris Heemskerks Bachelors thesis, 
# and is being re-used here. All rights are reserved to Joris Heemskerk, 
# and Technolution BV, Gouda NL. Joris was granted the rights to use and 
# modify this code, at the express notion that a disclaimer was put in.

# Default environment yaml file
# NOTE: See assignment_4/config/config_validation_template.py for the 
# parameter restrictions.

general:
    num_data_workers: 4 # Number of workers preparing batches.
jobs:
    job0:
        model: "LSTM"
        input_size: 5
        hidden_size: [20]
        num_layers: 1
        optimiser: "adam"
        train_val_split: [.8, .2]
        batch_size: 8
        n_epochs: 20
        learning_rate: .0001 # 1e-4
